import esbuild from "esbuild";
import process from "node:process";
import { resolveBuildIdentity } from "./scripts/build-identity.mjs";
import { resolveRecantaManifest } from "./scripts/recanta-manifest.mjs";

const production = process.argv.includes("production");
// Production builds must be reproducible from a release tag, so they always
// carry the stable release identity. Watch/dev builds keep the short commit so
// a sideloaded development bundle can still identify exactly what produced it.
const buildId = production && process.env.WB_BUILD_CHANNEL !== "dev"
	? resolveBuildIdentity({ ...process.env, WB_BUILD_CHANNEL: "release" })
	: resolveBuildIdentity();

const banner = `/*
WritingBuddy / 墨伴 — Obsidian plugin bundle.
This file is generated by esbuild. Edit the sources under src/ instead.
*/
`;

/** @type {import("esbuild").BuildOptions} */
const options = {
	banner: { js: banner },
	// The embedded engine's identity is fixed at build time from the exact pinned commit.
	define: { __WB_BUILD_ID__: JSON.stringify(buildId), __WB_RECANTA__: JSON.stringify(await resolveRecantaManifest()) },
	// The engine is bundled from the copy this repository carries, so the public
	// snapshot builds the same bytes as the development tree without reaching for
	// a dependency only its author can install.
	alias: {
		"recanta-dev": "./vendor/recanta/dist/src/index.js",
		"recanta-dev/sqljs": "./vendor/recanta/dist/src/drivers/sqljs.js",
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	// Everything Obsidian supplies at runtime, plus Electron/Node built-ins,
	// must stay external so the bundle is loadable inside the app.
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"node:fs",
		"node:path",
		"node:os",
	],
	format: "cjs",
	// SQLite-WASM for novel memory is embedded as bytes: no file next to
	// main.js, no code fetched at run time, one bundle for desktop and mobile.
	loader: { ".wasm": "binary" },
	target: "es2022",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	// Never minified: a Community-plugin reviewer, and anyone who opens the
	// installed main.js, reads the same code that is in this repository.
	minify: false,
	// Tests build into a private location so they never share main.js with a deploy or another test.
	outfile: process.env.WB_BUILD_OUTFILE || "main.js",
	platform: "browser",
};

if (production) {
	await esbuild.build(options);
} else {
	const ctx = await esbuild.context(options);
	await ctx.watch();
}
