import esbuild from "esbuild";
import process from "node:process";
import { resolveBuildIdentity } from "./scripts/build-identity.mjs";

const production = process.argv.includes("production");
// Which build this is, decided here and frozen into the bundle: a development
// build carries the short commit; WB_BUILD_CHANNEL=release makes a release.
const buildId = resolveBuildIdentity();

const banner = `/*
WritingBuddy / 墨伴 — Obsidian plugin bundle.
This file is generated by esbuild. Edit the sources under src/ instead.
*/
`;

/** @type {import("esbuild").BuildOptions} */
const options = {
	banner: { js: banner },
	define: { __WB_BUILD_ID__: JSON.stringify(buildId) },
	entryPoints: ["src/main.ts"],
	bundle: true,
	// Everything Obsidian supplies at runtime, plus Electron/Node built-ins,
	// must stay external so the bundle is loadable inside the app.
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"node:fs",
		"node:path",
		"node:os",
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: production ? false : "inline",
	treeShaking: true,
	// Never minified: a Community-plugin reviewer, and anyone who opens the
	// installed main.js, reads the same code that is in this repository.
	minify: false,
	outfile: "main.js",
	platform: "browser",
};

if (production) {
	await esbuild.build(options);
} else {
	const ctx = await esbuild.context(options);
	await ctx.watch();
}
