import type { ProjectStore, StoredSkillFile } from "../storage/ProjectStore";
import { CUSTOM_SKILLS_DIR, SKILLS_DIR, SKILL_OVERRIDES_DIR } from "../storage/paths";
import {
	findHistoricalBuiltin,
	findCanonicalHistoricalBuiltin,
	hashSkillSource,
	isHistoricalBuiltinId,
} from "./skillCatalog";
import { BUILTIN_SKILLS } from "./builtinSkills";
import { parseSkill, serializeSkill, type SkillFileMetadata } from "./skillParser";
import { randomId } from "../util/id";

export const SKILL_MIGRATION_SCHEMA_VERSION = 1;

export type LegacySkillClassification =
	| "seeded-mirror"
	| "legacy-custom"
	| "legacy-customization"
	| "legacy-customization-reset"
	| "malformed";

export type SkillMigrationState = "destination-modified";

export interface SkillMigrationEntry {
	path: string;
	/** Hash of the current retained legacy source. */
	hash: string;
	classification: LegacySkillClassification;
	destination: string | null;
	/** Exact destination bytes observed when this entry was recorded. */
	destinationHash?: string;
	/** Expected output for `hash` when a writer-edited destination blocks replacement. */
	pendingDestinationHash?: string;
	/** Source revision that previously owned `destination`, retained for review. */
	previousSourceHash?: string;
	/** Prior generated override removed by an explicit Reset action. */
	resetDestination?: string;
	/** Exact override bytes removed by the explicit Reset action. */
	resetDestinationHash?: string;
	/** Deterministic integrity receipt over the reset transition. */
	resetReceipt?: string;
	state?: SkillMigrationState;
	detail?: string;
}

export interface SkillMigrationManifest {
	schemaVersion: 1;
	sources: SkillMigrationEntry[];
}

export interface SkillMigrationReport {
	manifest: SkillMigrationManifest;
	written: string[];
	problems: Array<{ path: string; reason: string }>;
}

interface SkillResetState {
	schemaVersion: 1;
	receipts: SkillResetRecord[];
}

interface SkillResetRecord {
	receipt: string;
	sourcePath: string;
	sourceHash: string;
	destination: string;
	destinationHash: string;
}

interface ClassifiedSource {
	classification: LegacySkillClassification;
	destinationDirectory?: typeof CUSTOM_SKILLS_DIR | typeof SKILL_OVERRIDES_DIR;
	contents?: string;
	detail?: string;
}

interface ResolvedDestination {
	destination: string;
	destinationHash: string;
	conflict?: string;
}

export interface RemovedSkillDestination {
	path: string;
	hash: string;
}

/**
 * Classify and, where safe, copy legacy flat skill files into owned storage.
 * Sources are never modified or removed. The ledger records both the current
 * source hash and the exact generated bytes. A changed source is reconciled
 * with the one active same-id destination without ever overwriting based only
 * on claims in a writer-editable manifest.
 */
export async function migrateLegacySkillFiles(
	store: ProjectStore,
	legacyFiles: readonly StoredSkillFile[],
): Promise<SkillMigrationReport> {
	const existingRaw = await store.readSkillMigrationManifest();
	const decoded = parseManifest(existingRaw);
	const resetReceipts = await readResetReceipts(store);
	if (legacyFiles.length === 0 && existingRaw === null) {
		return { manifest: decoded, written: [], problems: [] };
	}

	const directFiles = [...legacyFiles]
		.filter((file) => isDirectLegacyMarkdownPath(file.path))
		.sort((left, right) => left.path.localeCompare(right.path));
	const currentPaths = new Set(directFiles.map((file) => file.path));
	const previousByPath = uniqueEntriesForCurrentSources(decoded.sources, currentPaths);
	const sources: SkillMigrationEntry[] = [];
	const written: string[] = [];
	const problems: Array<{ path: string; reason: string }> = [];

	for (const file of legacyFiles) {
		if (!isDirectLegacyMarkdownPath(file.path)) {
			problems.push({ path: file.path, reason: "legacy skill must be a direct Markdown child of WritingBuddy/skills" });
		}
	}

	for (const file of directFiles) {
		let source: string;
		try {
			source = await store.readSkillFile(file.path);
		} catch (error) {
			problems.push({ path: file.path, reason: (error as Error).message });
			continue;
		}

		const hash = hashSkillSource(source);
		const previous = previousByPath.get(file.path);
		const reset = resetRecordFor(resetReceipts, source, file.path, hash);
		if (reset) {
			// Sync may deliver the override deletion, reset ledger, and migration
			// manifest in any order. Remove only an exact stale copy of the override
			// that Reset deleted; a different current customization is left active.
			if (await store.fileExists(reset.destination)) {
				const current = await store.readSkillFile(reset.destination);
				if (hashSkillSource(current) === reset.destinationHash) {
					await store.removeSkillFile(reset.destination);
				}
			}
			sources.push({
				path: file.path, hash, classification: "legacy-customization-reset", destination: null,
				resetDestination: reset.destination, resetDestinationHash: reset.destinationHash,
				resetReceipt: reset.receipt, detail: "Writer explicitly reset the migrated built-in customization.",
			});
			continue;
		}
		const classified = classifySource(source, file.path, hash);
		if (classified.contents === undefined || classified.destinationDirectory === undefined) {
			const entry: SkillMigrationEntry = {
				path: file.path,
				hash,
				classification: classified.classification,
				destination: null,
				...(classified.detail ? { detail: classified.detail } : {}),
			};
			sources.push(entry);
			if (classified.classification === "malformed") {
				problems.push({ path: file.path, reason: classified.detail ?? "malformed legacy skill" });
			}
			continue;
		}

		const desiredHash = hashSkillSource(classified.contents);
		const resolved = await resolveDestination(
			store,
			classified.destinationDirectory,
			file.path,
			hash,
			classified.contents,
			previous,
			written,
		);
		if (resolved.conflict) {
			const previousSourceHash = previous?.hash === hash
				? previous.previousSourceHash
				: previous?.hash;
			const entry: SkillMigrationEntry = {
				path: file.path,
				hash,
				classification: classified.classification,
				destination: resolved.destination,
				destinationHash: resolved.destinationHash,
				pendingDestinationHash: desiredHash,
				...(previousSourceHash ? { previousSourceHash } : {}),
				state: "destination-modified",
				detail: resolved.conflict,
			};
			sources.push(entry);
			problems.push({ path: file.path, reason: resolved.conflict });
			continue;
		}

		sources.push({
			path: file.path,
			hash,
			classification: classified.classification,
			destination: resolved.destination,
			destinationHash: resolved.destinationHash,
			...(classified.detail ? { detail: classified.detail } : {}),
		});
	}

	const manifest: SkillMigrationManifest = {
		schemaVersion: SKILL_MIGRATION_SCHEMA_VERSION,
		sources: sources.sort((left, right) => left.path.localeCompare(right.path)),
	};
	const next = `${JSON.stringify(manifest, null, "\t")}\n`;
	if (next !== existingRaw) await store.writeSkillMigrationManifest(next);
	return { manifest, written, problems };
}

/**
 * Make an explicit Reset durable for migrated built-in customizations. Only a
 * valid entry whose exact destination was just removed is converted; all other
 * ledger entries and every retained legacy source remain untouched.
 */
export async function markLegacyCustomizationsReset(
	store: ProjectStore,
	removedDestinations: readonly RemovedSkillDestination[],
): Promise<void> {
	if (removedDestinations.length === 0) return;
	const raw = await store.readSkillMigrationManifest();
	if (raw === null) return;
	const manifest = parseManifest(raw);
	const resetReceipts = await readResetReceipts(store);
	const removed = new Map(removedDestinations.map((entry) => [entry.path, entry.hash]));
	let changed = false;
	const sources: SkillMigrationEntry[] = [];
	for (const entry of manifest.sources) {
		if (entry.classification !== "legacy-customization" ||
			entry.destination === null || !removed.has(entry.destination)) {
			sources.push(entry);
			continue;
		}
		try {
			if (!(await store.fileExists(entry.path))) {
				sources.push(entry);
				continue;
			}
			const source = await store.readSkillFile(entry.path);
			const classified = classifySource(source, entry.path, entry.hash);
			const removedHash = removed.get(entry.destination);
			if (hashSkillSource(source) !== entry.hash || classified.classification !== "legacy-customization" ||
				removedHash === undefined) {
				sources.push(entry);
				continue;
			}
			// A fresh opaque nonce, recorded independently in resets.json, proves
			// this transition came through the explicit Reset operation. The older
			// deterministic hash could be reconstructed from manifest fields alone.
			const receipt = createResetReceipt();
			resetReceipts.set(receipt, {
				receipt, sourcePath: entry.path, sourceHash: entry.hash,
				destination: entry.destination, destinationHash: removedHash,
			});
			sources.push({
				path: entry.path,
				hash: entry.hash,
				classification: "legacy-customization-reset",
				destination: null,
				resetDestination: entry.destination,
				resetDestinationHash: removedHash,
				resetReceipt: receipt,
				detail: "Writer explicitly reset the migrated built-in customization.",
			});
			changed = true;
		} catch {
			// A concurrently changed/unreadable source cannot be safely tombstoned.
			sources.push(entry);
		}
	}
	if (!changed) return;
	await writeResetReceipts(store, resetReceipts);
	const next: SkillMigrationManifest = {
		schemaVersion: SKILL_MIGRATION_SCHEMA_VERSION,
		sources: sources.sort((left, right) => left.path.localeCompare(right.path)),
	};
	await store.writeSkillMigrationManifest(`${JSON.stringify(next, null, "\t")}\n`);
}

function classifySource(source: string, path: string, hash: string): ClassifiedSource {
	const parsed = parseSkill(source, path);
	if (!parsed.ok) {
		return { classification: "malformed", detail: parsed.reason };
	}

	const normalizedHash = hashSkillSource(source.replace(/^﻿/u, "").replace(/\r\n?/gu, "\n"));
	const historical = findHistoricalBuiltin(parsed.skill.id, hash) ??
		findHistoricalBuiltin(parsed.skill.id, normalizedHash) ??
		findCanonicalHistoricalBuiltin(parsed.skill.id, source);
	if (historical) {
		return {
			classification: "seeded-mirror",
			detail: `WritingBuddy ${historical.releases.join(", ")}`,
		};
	}

	if (isHistoricalBuiltinId(parsed.skill.id) && CURRENT_BUILTIN_IDS.has(parsed.skill.id)) {
		const metadata: SkillFileMetadata = {
			schemaVersion: 1,
			// A legacy full skill cannot safely be reduced to a delta. Preserve its
			// effective behavior as an explicit replacement for review.
			mode: "replace",
		};
		return {
			classification: "legacy-customization",
			destinationDirectory: SKILL_OVERRIDES_DIR,
			contents: replacementSource(source, parsed.skill, metadata),
			detail: "Base could not be identified; preserved as an explicit replacement for review.",
		};
	}

	return {
		classification: "legacy-custom",
		destinationDirectory: CUSTOM_SKILLS_DIR,
		contents: source,
	};
}

const CURRENT_BUILTIN_IDS = new Set(BUILTIN_SKILLS.map((skill) => skill.id));

function replacementSource(source: string, skill: Parameters<typeof serializeSkill>[0], metadata: SkillFileMetadata): string {
	const frontmatter = /^﻿?\s*---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*(?:\r?\n|$)/u.exec(source)?.[1];
	if (frontmatter === undefined) return serializeSkill(skill, metadata);
	const preserved: string[] = [];
	for (const rawLine of frontmatter.split(/\r?\n/u)) {
		const separator = rawLine.indexOf(":");
		if (separator <= 0) {
			if (rawLine.trim().length > 0) preserved.push(rawLine);
			continue;
		}
		const key = rawLine.slice(0, separator).trim().toLowerCase();
		if (!SERIALIZED_SKILL_KEYS.has(key)) preserved.push(rawLine);
	}
	const serialized = serializeSkill(skill, metadata);
	return preserved.length === 0
		? serialized
		: serialized.replace(/^---\n/u, `---\n${preserved.join("\n")}\n`);
}

const SERIALIZED_SKILL_KEYS = new Set([
	"schemaversion", "id", "name", "action", "scope", "version", "description",
	"composerprompt", "instructionprofile", "routing", "routingallowquestions", "triggers",
	"mode", "baseversion", "basehash",
]);

function resetRecordFor(
	resetReceipts: ReadonlyMap<string, SkillResetRecord>,
	source: string,
	path: string,
	hash: string,
): SkillResetRecord | undefined {
	const classified = classifySource(source, path, hash);
	if (classified.classification !== "legacy-customization") return undefined;
	return [...resetReceipts.values()].find((record) =>
		record.sourcePath === path && record.sourceHash === hash &&
		isDirectChild(record.destination, SKILL_OVERRIDES_DIR));
}

function createResetReceipt(): string {
	return hashSkillSource(`reset-v2:${randomId(48)}:${Date.now()}`);
}

async function readResetReceipts(store: ProjectStore): Promise<Map<string, SkillResetRecord>> {
	try {
		const raw = await store.readSkillResetState();
		if (raw === null) return new Map();
		const decoded = JSON.parse(raw) as Partial<SkillResetState>;
		if (decoded.schemaVersion !== 1 || !Array.isArray(decoded.receipts)) return new Map();
		return new Map(decoded.receipts.flatMap((value): Array<[string, SkillResetRecord]> => {
			if (!isResetRecord(value)) return [];
			return [[value.receipt, value]];
		}));
	} catch {
		return new Map();
	}
}

async function writeResetReceipts(store: ProjectStore, receipts: ReadonlyMap<string, SkillResetRecord>): Promise<void> {
	const state: SkillResetState = {
		schemaVersion: 1,
		receipts: [...receipts.values()].sort((left, right) => left.receipt.localeCompare(right.receipt)),
	};
	await store.writeSkillResetState(`${JSON.stringify(state, null, "\t")}\n`);
}

function isResetRecord(value: unknown): value is SkillResetRecord {
	if (typeof value !== "object" || value === null) return false;
	const record = value as Record<string, unknown>;
	return isSha256(record.receipt) && isDirectLegacyMarkdownPath(String(record.sourcePath)) &&
		isSha256(record.sourceHash) && typeof record.destination === "string" &&
		isDirectChild(record.destination, SKILL_OVERRIDES_DIR) && isSha256(record.destinationHash);
}

async function resolveDestination(
	store: ProjectStore,
	directory: typeof CUSTOM_SKILLS_DIR | typeof SKILL_OVERRIDES_DIR,
	sourcePath: string,
	sourceHash: string,
	contents: string,
	previous: SkillMigrationEntry | undefined,
	written: string[],
): Promise<ResolvedDestination> {
	const desired = parseSkill(contents, sourcePath);
	const desiredId = desired.ok ? desired.skill.id : undefined;

	if (previous?.destination && isDirectChild(previous.destination, directory)) {
		const priorPath = previous.destination;
		if (await store.fileExists(priorPath)) {
			const actual = await store.readSkillFile(priorPath);
			if (actual === contents) {
				return { destination: priorPath, destinationHash: hashSkillSource(actual) };
			}

			const actualParsed = parseSkill(actual, priorPath);
			if (desiredId !== undefined && actualParsed.ok && actualParsed.skill.id === desiredId) {
				return {
					destination: priorPath,
					destinationHash: hashSkillSource(actual),
					conflict: destinationConflict(sourcePath, desiredId, priorPath),
				};
			}
		}
	}

	const stored = await store.listStoredSkillFiles({ includeLegacy: false });
	const location = directory === CUSTOM_SKILLS_DIR ? "custom" : "override";
	const files = stored
		.filter((file) => file.location === location && isDirectChild(file.path, directory))
		.sort((left, right) => left.path.localeCompare(right.path));
	const byPath = new Map<string, string>();
	let sameIdPath: string | undefined;
	for (const file of files) {
		const existing = await store.readSkillFile(file.path);
		byPath.set(file.path, existing);
		if (existing === contents) return { destination: file.path, destinationHash: hashSkillSource(existing) };
		if (desiredId !== undefined) {
			const parsed = parseSkill(existing, file.path);
			if (parsed.ok && parsed.skill.id === desiredId) sameIdPath ??= file.path;
		}
	}
	if (sameIdPath) {
		return {
			destination: sameIdPath,
			destinationHash: hashSkillSource(byPath.get(sameIdPath) ?? ""),
			conflict: destinationConflict(sourcePath, desiredId, sameIdPath),
		};
	}

	for (let index = 0; ; index += 1) {
		const candidate = destinationCandidate(directory, sourcePath, sourceHash, index);
		const cached = byPath.get(candidate);
		if (cached !== undefined) {
			if (cached === contents) return { destination: candidate, destinationHash: hashSkillSource(cached) };
			continue;
		}
		if (await store.fileExists(candidate)) {
			// The path may be a folder or a file created since enumeration. Never
			// overwrite either kind of collision.
			try {
				const collision = await store.readSkillFile(candidate);
				if (collision === contents) return { destination: candidate, destinationHash: hashSkillSource(collision) };
			} catch {
				// A non-file collision is simply unavailable.
			}
			continue;
		}
		await store.writeSkillFile(candidate, contents);
		written.push(candidate);
		return { destination: candidate, destinationHash: hashSkillSource(contents) };
	}
}

function destinationConflict(sourcePath: string, id: string | undefined, destination: string): string {
	return `Legacy source ${sourcePath} targets skill id \`${id ?? "unknown"}\`, but ${destination} contains different active content; preserved the active destination and did not overwrite it.`;
}

function destinationCandidate(
	directory: string,
	sourcePath: string,
	hash: string,
	index: number,
): string {
	const filename = sourcePath.split("/").pop() ?? `legacy-${hash.slice(0, 12)}.md`;
	if (index === 0) return `${directory}/${filename}`;
	const extension = filename.toLowerCase().endsWith(".md") ? filename.slice(-3) : ".md";
	const stem = filename.slice(0, filename.length - extension.length);
	const ordinal = index === 1 ? "" : `-${index}`;
	return `${directory}/${stem}-legacy-${hash.slice(0, 12)}${ordinal}${extension}`;
}

function parseManifest(raw: string | null): SkillMigrationManifest {
	if (raw === null) return { schemaVersion: 1, sources: [] };
	try {
		const decoded = JSON.parse(raw) as Record<string, unknown>;
		if (decoded.schemaVersion !== 1 || !Array.isArray(decoded.sources)) {
			return { schemaVersion: 1, sources: [] };
		}
		return { schemaVersion: 1, sources: decoded.sources.filter(isManifestEntry) };
	} catch {
		return { schemaVersion: 1, sources: [] };
	}
}

function isManifestEntry(value: unknown): value is SkillMigrationEntry {
	if (typeof value !== "object" || value === null) return false;
	const entry = value as Record<string, unknown>;
	if (typeof entry.path !== "string" || !isDirectLegacyMarkdownPath(entry.path)) return false;
	if (!isSha256(entry.hash) || !isClassification(entry.classification)) return false;
	if (entry.detail !== undefined && typeof entry.detail !== "string") return false;
	if (entry.destinationHash !== undefined && !isSha256(entry.destinationHash)) return false;
	if (entry.pendingDestinationHash !== undefined && !isSha256(entry.pendingDestinationHash)) return false;
	if (entry.previousSourceHash !== undefined && !isSha256(entry.previousSourceHash)) return false;
	if (entry.resetDestination !== undefined && typeof entry.resetDestination !== "string") return false;
	if (entry.resetDestinationHash !== undefined && !isSha256(entry.resetDestinationHash)) return false;
	if (entry.resetReceipt !== undefined && !isSha256(entry.resetReceipt)) return false;
	if (entry.state !== undefined && entry.state !== "destination-modified") return false;

	if (entry.classification === "legacy-customization-reset") {
		return entry.destination === null && entry.destinationHash === undefined &&
			entry.pendingDestinationHash === undefined && entry.previousSourceHash === undefined && entry.state === undefined &&
			typeof entry.resetDestination === "string" && isDirectChild(entry.resetDestination, SKILL_OVERRIDES_DIR) &&
			isSha256(entry.resetDestinationHash) && isSha256(entry.resetReceipt);
	}
	if (entry.classification === "seeded-mirror" || entry.classification === "malformed") {
		return entry.destination === null && entry.destinationHash === undefined &&
			entry.pendingDestinationHash === undefined && entry.previousSourceHash === undefined && entry.state === undefined &&
			entry.resetDestination === undefined && entry.resetDestinationHash === undefined && entry.resetReceipt === undefined;
	}
	if (entry.resetDestination !== undefined || entry.resetDestinationHash !== undefined || entry.resetReceipt !== undefined) return false;
	if (typeof entry.destination !== "string") return false;
	const root = entry.classification === "legacy-custom" ? CUSTOM_SKILLS_DIR : SKILL_OVERRIDES_DIR;
	if (!isDirectChild(entry.destination, root)) return false;
	if (entry.state === "destination-modified") {
		return isSha256(entry.destinationHash) && isSha256(entry.pendingDestinationHash);
	}
	return entry.pendingDestinationHash === undefined && entry.previousSourceHash === undefined;
}

function uniqueEntriesForCurrentSources(
	entries: readonly SkillMigrationEntry[],
	currentPaths: ReadonlySet<string>,
): Map<string, SkillMigrationEntry> {
	const unique = new Map<string, SkillMigrationEntry>();
	const duplicates = new Set<string>();
	for (const entry of entries) {
		if (!currentPaths.has(entry.path)) continue;
		if (unique.has(entry.path)) {
			unique.delete(entry.path);
			duplicates.add(entry.path);
			continue;
		}
		if (!duplicates.has(entry.path)) unique.set(entry.path, entry);
	}
	return unique;
}

function isClassification(value: unknown): value is LegacySkillClassification {
	return ["seeded-mirror", "legacy-custom", "legacy-customization", "legacy-customization-reset", "malformed"].includes(String(value));
}

function isSha256(value: unknown): value is string {
	return typeof value === "string" && /^[a-f0-9]{64}$/u.test(value);
}

function isDirectLegacyMarkdownPath(path: string): boolean {
	return isDirectChild(path, SKILLS_DIR);
}

function isDirectChild(path: string, directory: string): boolean {
	if (!path.startsWith(`${directory}/`) || !path.toLowerCase().endsWith(".md")) return false;
	const relative = path.slice(directory.length + 1);
	return relative.length > 3 && !relative.includes("/") && !relative.includes("\\") &&
		relative !== "." && relative !== "..";
}
